name: Authorize Salesforce Org

on:
  push:
    branches:
      - Developer

jobs:
  authorize-salesforce:
    runs-on: ubuntu-latest

    env:
      SALESFORCE_CONSUMER_KEY: ${{ secrets.SFDC_CONSUMER_KEY_DEVELOPER_ORG }}
      SALESFORCE_CONSUMER_SECRET: ${{ secrets.SFDC_CONSUMER_SECRET_DEVELOPER_ORG }}
      SALESFORCE_USERNAME: ${{ secrets.SFDC_USERNAME_DEVELOPER_ORG }}
      SALESFORCE_PASSWORD: ${{ secrets.SFDC_PASSWORD_DEVELOPER_ORG }}
      SALESFORCE_SECURITY_TOKEN: ${{ secrets.SFDC_SECURITY_TOKEN_DEVELOPER_ORG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authorize Salesforce Org
        run: |
          ACCESS_TOKEN=$(curl -d "grant_type=password" -d "client_id=$SALESFORCE_CONSUMER_KEY" -d "client_secret=$SALESFORCE_CONSUMER_SECRET" -d "username=$SALESFORCE_USERNAME" -d "password=$SALESFORCE_PASSWORD$SALESFORCE_SECURITY_TOKEN" https://test.salesforce.com/services/oauth2/token | jq -r .access_token)

          echo "::set-output name=ACCESS_TOKEN::$ACCESS_TOKEN"
