name: Deploy to Sandbox

on:
  push:
    branches:
      - Developer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Sandbox
        run: |
          # Add your deployment commands here
          sfdx force:source:deploy -u sandbox -p force-app/main/default

          # For example, if deploying to a server, use SSH or other deployment tools.
          # If deploying to a cloud service, use the respective CLI.