name: Deploy to Sandbox

on:
  push:
    branches:
      - Developer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authorization to Sandbox
        run: |
        echo "${{ secrets.JWT_PRIVATE_KEY }}" > server.key
        sfdx force:auth:jwt:grant --clientid ${{ secrets.SFDC_CONSUMER_KEY_DEVELOPER_ORG }} --jwtkeyfile ./server.key --username ${{ secrets.SFDC_SANDBOX_USERNAME_DEVELOPER_ORG }} --instanceurl ${{ secrets.SFDC_SANDBOX_URL }} --setdefaultdevhubusername -a sandbox

      - name: Deploy to Sandbox
        run: |
          sfdx force:source:deploy -u sandbox -p force-app/main/default
           # Add your deployment commands here
           # For example, if deploying to a server, use SSH or other deployment tools.
           # If deploying to a cloud service, use the respective CLI.
