name: Deploy to Salesforce Sandbox

on:
  push:
    branches:
      - Developer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Salesforce CLI
        run: 
          command: |
            npm install --global sfdx-cli
            name: Install SFDX

      - name: Authorize Salesforce Org
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.SFDC_CONSUMER_KEY_DEVELOPER_ORG }} --jwtkeyfile ./path/to/server.key --username ${{ secrets.SFDC_USERNAME_DEVELOPER_ORG }} --setdefaultdevhubusername -a sfdc-sandbox

      - name: Deploy to Salesforce Sandbox
        run: sfdx force:source:deploy -u sfdc-sandbox -p force-app/main/default

