name: Deploy to Salesforce Sandbox

on:
  push:
    branches:
      - Developer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Salesforce CLI
        run: 
            npm install --global sfdx-cli

      - name: Authorize Salesforce Org
        run: |
          ACCESS_TOKEN=$(curl -d "grant_type=password" -d "client_id=${{ secrets.SFDC_CONSUMER_KEY_DEVELOPER_ORG }}" -d "client_secret=${{ secrets.SFDC_CONSUMER_KEY_DEVELOPER_ORG }}" -d "username=${{ secrets.SFDC_USERNAME_DEVELOPER_ORG }}" -d "password=${{ secrets.SFDC_PASSWORD_DEVELOPER_ORG }}${{ secrets.SFDC_SECURITY_TOKEN_DEVELOPER_ORG }}" ${{ secrets.SFDC_SANDBOX_URL }}/services/oauth2/token | jq -r .access_token)

      - name: Deploy to Salesforce Sandbox
        run: sfdx force:source:deploy -u sfdc-sandbox -p force-app/main/default

