name: Deploy to Salesforce Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        run: |
          echo "Installing Salesforce CLI"
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-linux-x64.tar.xz
          mkdir sfdx
          tar xJf sfdx-cli-linux-x64.tar.xz -C sfdx --strip-components 1
          export PATH=$PWD/sfdx/bin:$PATH
          sfdx --version

      - name: Authorize Salesforce Org
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.SFDC_CONSUMER_KEY_DEVELOPER_ORG }} --jwtkeyfile ./path/to/server.key --username ${{ secrets.SFDC_USERNAME_DEVELOPER_ORG }} --setdefaultdevhubusername -a sfdc-sandbox

      - name: Deploy to Salesforce Sandbox
        run: sfdx force:source:deploy -u sfdc-sandbox -p force-app/main/default

