name: Deploy to Sandbox

on:
  push:
    branches:
      - Developer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Sandbox
        run: |
          ssh ${{ secrets.SFDC_USERNAME_DEVELOPER_ORG }} '/Users/pawankumar/Documents/Project/deployment-github-action/manifest/package.xml'
           # Add your deployment commands here
           # For example, if deploying to a server, use SSH or other deployment tools.
           # If deploying to a cloud service, use the respective CLI.
