name: Deploy to Sandbox

on:
  push:
    branches:
      - Developer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authorization to Sandbox
        env:
        DEPLOYMENT_API_KEY: ${{ secrets.DEPLOYMENT_API_KEY }}
      
      - name: Deploy to Sandbox
        run: |
          sfdx force:source:deploy -u sandbox -p force-app/main/default
           # Add your deployment commands here
           # For example, if deploying to a server, use SSH or other deployment tools.
           # If deploying to a cloud service, use the respective CLI.
      
      - name: Run Tests in Sandbox
      run: |
        sfdx force:apex:test:run -u sandbox

    - name: Disconnect from Sandbox
      run: |
        sfdx force:auth:logout -u sandbox     
