name: Deploy to Sandbox

on:
  push:
    branches:
      - Developer

jobs:
  Build:
    runs-on: ubuntu-latest

    - name: Install the SFDX CLI
      run: |
      npm install @salesforce/cli --global
      sf --help

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Sandbox
        run: |
          sfdx force:source:deploy -u sandbox -p force-app/main/default
           # Add your deployment commands here
           # For example, if deploying to a server, use SSH or other deployment tools.
           # If deploying to a cloud service, use the respective CLI.
